# This file configures your Netlify deployment.
# It includes a scheduled function to periodically fetch news headlines.

# Build settings for your Next.js app
[build]
  command = "npm run build"
  publish = ".next"

# Configuration for Netlify Functions
# The `fetch-news-cron` function is a scheduled function.
# The cron schedule "0 */2 * * *" means "at minute 0 of every 2nd hour".
# This helps stay within the GNews API free tier limits.
[functions]
  directory = "netlify/functions"

[functions.fetch-news-cron]
  schedule = "0 */2 * * *"
